name: Generate preview link

on:
    push:
        branches:
            - main

jobs:
    install_modules:
        runs-on: Ubuntu-latest
        steps:
            - name: Checkout to repo
              uses: actions/checkout@v4
            
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: Install dependency
              run: npm install

            - name: Upload node modules
              uses: actions/upload-artifact@v4
              with:
                name: node_modules
                path: node_modules

    build_and_publish_row:
        needs: install_modules
        runs-on: Ubuntu-latest
        steps:
            - name: Checkout to repo
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: node_modules
                path: node_modules

            - name: List downloaded files
              run: ls -l

            - name: Check if node_modules exists
              run: test -d node_modules || echo "node_modules directory not found"

            - name: Set permissions for node_modules
              run: chmod -R 755 node_modules

            - name: Build row
              run: npm run build:row